name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: debian-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SAIL_KEY }}  # Usa el secret de la clave privada

    - name: Deploy to Lightsail
      env:
        SERVER_USER: ${{ secrets.SERVER_USER }}  # Usa el secret del usuario
        SERVER_IP: ${{ secrets.SERVER_IP }}      # Usa el secret de la IP del servidor
        PROJECT_PATH: /home/admin/portfolio2
      run: |
        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
          cd $PROJECT_PATH
          git pull origin main
          npm install
          npm run build
          pm2 restart portfolio-app
        EOF
